name: past_paper_master
description: Past Paper Master.

publish_to: "none"

version: 0.1.6+65

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  window_manager: ^0.2.8
  flutter_svg: ^1.1.6
  ionicons: ^0.2.1
  provider: ^6.0.5
  flutter_feather_icons: ^2.0.0
  rive: ^0.11.17
  dropdown_button2: ^1.9.2
  path_provider: ^2.0.11
  shared_preferences: ^2.0.16
  uuid: ^4.3.3
  file_picker: ^5.0.1
  dio: ^5.0.3
  url_launcher: ^6.1.5

  pdfrx: ^1.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/rive/
    - assets/images/
    - assets/json/
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Thin.otf
          weight: 100
        - asset: fonts/Inter-ExtraLight.otf
          weight: 200
        - asset: fonts/Inter-Light.otf
          weight: 300
        - asset: fonts/Inter-Regular.otf
          weight: 400
        - asset: fonts/Inter-Medium.otf
          weight: 500
        - asset: fonts/Inter-SemiBold.otf
          weight: 600
        - asset: fonts/Inter-Bold.otf
          weight: 700
        - asset: fonts/Inter-ExtraBold.otf
          weight: 800
        - asset: fonts/Inter-Black.otf
          weight: 900
